Add support for pandoc
arcticicestudio/nord-vim pull request #220
Opened 2020-08-02 20:48 UTC by tpoisot

The current version of `nord-vim` does not have support for most syntax elements from the `vim-pandoc-syntax` package (#207):

![before](https://user-images.githubusercontent.com/579329/89132103-a9d00800-d4df-11ea-9563-80d79d4ab5f9.png)

I have added support for these groups - notably, this solves the issues with `Conceal` (notably #211). This is the result with the additional syntax groups:

![after](https://user-images.githubusercontent.com/579329/89132102-a9d00800-d4df-11ea-880a-6a3295d33bea.png)

2020-08-07 18:43 UTC, BirgerNi commented
Hej @tpoisot,

just tested your pull request, good job. Do you use an option like `hi Conceal guibg=NONE ctermbg=NONE` in your `.vimrc`?

1) Pull request w/o conceal option in `.vimrc`
![1](https://user-images.githubusercontent.com/21315429/89677537-ea6bbf00-d8ed-11ea-8d70-89c605122fad.png)

2) Pull request w/ conceal option in `.vimrc`
![2](https://user-images.githubusercontent.com/21315429/89677565-f48dbd80-d8ed-11ea-876c-fb605eb3f47c.png)

3) develop branch w/ conceal option in `.vimrc`
![3](https://user-images.githubusercontent.com/21315429/89677590-02434300-d8ee-11ea-93f6-043edb2164fc.png)

2020-08-08 15:01 UTC, tpoisot commented
You're right, I did have that! Should it be added to the theme? I'm not sure how it can interact with other packages.

2020-08-08 18:13 UTC, BirgerNi commented
I'm okay with that. I guess at least some documentation would be nice for new users. Any thoughts @arcticicestudio ?

2021-04-21 21:25 UTC, lompabo commented
Anyone for reviewing this? Pandoc support is currently the main factor preventing me from switching to this theme

2021-05-29 10:34 UTC, arcticicestudio requested changes
Hi @tpoisot :wave:, thanks for your contribution :+1:

Thanks for your patience, the large amount of tasks for the Nord project are really time consuming and free time is kind of rare.
I've suggested some changes to make it more consistent with existing theme styles. Let me know what you think about it.

<img src="https://user-images.githubusercontent.com/7836623/120067101-1f622180-c07a-11eb-81a0-73414e54df55.png" width="600px" />

2021-05-29 10:34 UTC, arcticicestudio commented on colors/nord.vim
> +
I think linking most groups to existing Markdown groups should ensure to get a consistent style across languages and different plugins.

```suggestion
" Pandoc
" > vim-pandoc/vim-pandoc-syntax
call s:hi("pandocDefinitionBlockTerm", s:nord7_gui, "", s:nord7_term, "", s:italic, "")
call s:hi("pandocTableDelims", s:nord3_gui, "", s:nord3_term, "", "", "")
hi! link pandocAtxHeader markdownH1
hi! link pandocBlockQuote markdownBlockquote
hi! link pandocCiteAnchor Operator
hi! link pandocCiteKey pandocReferenceLabel
hi! link pandocDefinitionBlockMark Operator
hi! link pandocEmphasis markdownItalic
hi! link pandocFootnoteID pandocReferenceLabel
hi! link pandocFootnoteIDHead markdownLinkDelimiter
hi! link pandocFootnoteIDTail pandocFootnoteIDHead
hi! link pandocGridTableDelims pandocTableDelims
hi! link pandocGridTableHeader pandocTableDelims
hi! link pandocOperator Operator
hi! link pandocPipeTableDelims pandocTableDelims
hi! link pandocReferenceDefinition pandocReferenceLabel
hi! link pandocReferenceLabel markdownLinkText
hi! link pandocReferenceURL markdownUrl
hi! link pandocSimpleTableHeader pandocAtxHeader
hi! link pandocStrong markdownBold
hi! link pandocTableHeaderWord pandocAtxHeader
hi! link pandocUListItemBullet Operator

```

2021-06-08 01:00 UTC, tpoisot commented
@arcticicestudio - will have a look, thanks for the feedback!

2021-07-10 12:11 UTC, arcticicestudio commented
@tpoisot Let me know if you'd like to apply the suggestions so I can resolve the current merge conflicts.

2021-07-10 12:12 UTC, tpoisot commented
I would love to, hopefully I'll find the time next week

2021-07-10 18:19 UTC, tpoisot commented
I think the merge conflicts are gone!

2021-07-11 08:11 UTC, svengreb approved these changes

2021-07-11 08:11 UTC, arcticicestudio approved these changes
LGTM 👍🏼 Thanks again for your contribution.

2021-07-11 08:21 UTC, merged