add support for Lsp codelens
arcticicestudio/nord-vim pull request #266
Opened 2021-07-10 17:35 UTC by jan-xyz

code lenses are currently highlighted with the default color. This change adjusts it to make it less visually intrusive like comments. 

Before:
<img width="622" alt="125170561-cc6aa680-e1af-11eb-9a21-98bbdd62e821" src="https://user-images.githubusercontent.com/5249233/125171712-d1caef80-e1b5-11eb-8a40-95d7e2a79bbd.png">

After:
<img width="620" alt="Screenshot 2021-07-10 at 19 28 57" src="https://user-images.githubusercontent.com/5249233/125171722-da232a80-e1b5-11eb-9073-5fb3795d1136.png">

It is based on the VS code highlighting:
<img width="442" alt="Screenshot 2021-07-10 at 19 10 09" src="https://user-images.githubusercontent.com/5249233/125171724-e0b1a200-e1b5-11eb-8062-a64dacb1e06f.png">

2021-07-22 21:16 UTC, arcticicestudio commented
Hi @jan-xyz :wave:, thanks for your contribution :+1:
I'll try to test and review the changes this weekend.

2021-07-28 07:17 UTC, arcticicestudio requested changes
Thanks again for your contribution. I've added a small improvement suggestion, otherwise this looks good to me 👍🏻

2021-07-28 07:17 UTC, arcticicestudio commented on colors/nord.vim
> +call s:hi("LspCodeLens", s:nord3_gui_bright, "", s:nord3_term, "", s:italicize_comments, "")
Lets link this to [the custom `Comment` group][1] instead (append below the other LSP definitions).

```diff
- call s:hi("LspCodeLens", s:nord3_gui_bright, "", s:nord3_term, "", s:italicize_comments, "")
+ hi! link LspCodeLens Comment
```

[1]: https://github.com/arcticicestudio/nord-vim/blob/8d8b9bf8/colors/nord.vim#L276

2021-07-28 20:36 UTC, jan-xyz commented
Done! :) Thanks for the feedback! Would you appreciate another PR that moves other Comments to the custom group as well?

2021-08-08 09:08 UTC, jan-xyz commented
hey @arcticicestudio, any news on getting this merged? 😊

2021-09-05 16:08 UTC, arcticicestudio requested changes
Thanks for your patience, I was on vacation for the last few weeks and I deliberately ignored the "digital life" during this time 😄

I reconsidered my previous suggestion and have come to the conclusion that the `Comment` the group is not right there due to the `s:italicize_comments` variable. Users who enabled this option would see code lenses being rendered with italic font style for an element that is more or less part of the UI and not the syntax. I guess for now we should use the dedicated definition from [your initial PR commit][1] and maybe introduce a new custom highlighting group for elements like this later on. Sorry for this back and forth of changes 🙈

> Would you appreciate another PR that moves other Comments to the custom group as well?

A PR that adds a new custom group for UI elements like code lenses or linter messages (like mentioned above) would be very welcome.

[1]: https://github.com/arcticicestudio/nord-vim/pull/266/commits/b602a041e1f43b7a69740eb642f4fc0c61aa3e71

2021-09-05 16:24 UTC, jan-xyz commented
No need to apologize! I appreciate consistent behavior and as this is something new I totally understand that you haven't figured out and planned all of the quirks and bits yet! I'll see to it soon and I hope you had a great digital free vacation 🤗

2021-09-05 17:20 UTC, jan-xyz commented
@arcticicestudio I applied your requested changes

2021-09-05 18:59 UTC, svengreb approved these changes

2021-09-05 19:00 UTC, arcticicestudio approved these changes
Thanks, this will land in the next release with some other LSP and `tree-sitter` related improvements 🚀

2021-09-05 19:10 UTC, merged

2022-05-13 09:45 UTC, svengreb commented
<h5 align="center">Release Note Assets</h5>

<!-- <h6 align="center">Headline</h6> -->

<p align="center"><strong>Before</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/13448100/168257661-7c66b447-c3c8-4c0d-8ce7-cc728f1ec870.png" width="80%" /></p>

<p align="center"><strong>After</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/13448100/168257647-57a84bda-5e19-4ece-a482-a65892065064.png" width="80%" /></p>