Add support for LSPSignatureActiveParameter
arcticicestudio/nord-vim pull request #286
Opened 2022-01-22 18:51 UTC by cmoscofian

Currently when calling `vim.lsp.buf.signature_help` on a given
function/method nord does not highlight or differentiate in any way the
active parameter.

This PR adds an accent color (**`nord8`**) and an **underline** to the current
active parameter making it stand out.

Highlight group docs: https://github.com/neovim/neovim/blob/70db972e5fbcab39946ad8ac05472a693cf65b68/runtime/doc/lsp.txt#L456-L459

See it in action:
**Before**:
![nord-before-zoom](https://user-images.githubusercontent.com/59028844/150651620-9e3a78b1-a10f-42ee-a639-7155a54fe45e.png)

**After**:
![nord-after-zoom](https://user-images.githubusercontent.com/59028844/150651619-67d21428-2193-4c96-8f70-9c87997b40be.png)

**Live**:
![nord-1](https://user-images.githubusercontent.com/59028844/150651458-6db090fc-6d9a-4e48-9b44-55c933fe426d.gif)

2022-01-25 11:06 UTC, arcticicestudio commented
Hi @cmoscofian :wave:, thanks for your contribution :+1:
I'll review and test the changes within the next week(s).

2022-02-16 22:27 UTC, svengreb requested changes
The style looks good to me, but please move the code line into the [already existing Neovim LSP block][1] which is guarded for “vanilla” Vim users.

[1]: https://github.com/arcticicestudio/nord-vim/blob/b32592eb/colors/nord.vim#L594-L603

2022-02-18 13:49 UTC, cmoscofian commented
> The style looks good to me, but please move the code line into the [already existing Neovim LSP block](https://github.com/arcticicestudio/nord-vim/blob/b32592eb/colors/nord.vim#L594-L603) which is guarded for “vanilla” Vim users.

Yeap, no problem. Since you mentioned it I noticed that there are a few neovim specific definitions outside of that if statement, that were all introduced on version 0.5 (Diagnostics, NativeLSP and Treesitter).
- [LSPReference*](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L229-L232)
- [Diagnostic*](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L219-L227)
- [LspCodeLens](https://github.com/arcticicestudio/nord-vim/blob/b32592eb0842005d1d25de96e3964ccacd537039/colors/nord.vim#L593)
- [TreeSitter](https://github.com/arcticicestudio/nord-vim/blob/b32592eb0842005d1d25de96e3964ccacd537039/colors/nord.vim#L737)

Should I give a whirl at a minor refactor and just subject them all under the same specific condition checking for 0.5?

2022-02-19 13:16 UTC, svengreb approved these changes
Ah, I remember why the guard exists at all: in #282 we added support for the new groups and the ones that are guarded for Neovim version(s) `0.5.z` are the deprecated/renamed ones, but I wanted to keep them for backwards compatibility reasons.
We can move all Neovim specific groups that are currently not guarded into the [already existing block that checks if Neovim is used at all][1], but this is out of scope for this PR.

You can ignore my review comment and I'll merge this PR. Thanks again for contribution 🚀 

[1]: https://github.com/arcticicestudio/nord-vim/blob/b32592eb/colors/nord.vim#L739

2022-02-19 13:16 UTC, arcticicestudio approved these changes

2022-02-19 13:22 UTC, merged

2022-02-19 13:30 UTC, svengreb commented
<h5 align="center">Release Note Assets</h5>

<!-- <h6 align="center">Headline</h6> -->

<p align="center"><strong>Before</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/13448100/154802856-a3baa5f8-4606-41b6-986e-d4f7c509f313.png" width="80%" /></p>

<p align="center"><strong>After</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/13448100/154802854-5e1f7c7b-9468-4920-93c1-6c26ef2cb0ac.png" width="80%" /></p>