Add Gitsigns and Sneak support
arcticicestudio/nord-vim pull request #316
Opened 2022-05-27 13:55 UTC by jasonlong

This adds support for [Gitsigns](https://github.com/lewis6991/gitsigns.nvim) and [Sneak](https://github.com/justinmk/vim-sneak).

#### Gitsigns (for current line blame)
Matches `Comment`

<img width="595" alt="CleanShot 2022-05-27 at 09 47 54@2x" src="https://user-images.githubusercontent.com/6104/170713199-eca91256-0c42-49bc-8679-a3eb7ccb4ac3.png">

#### Sneak
Matches `Search`

<img width="622" alt="CleanShot 2022-05-27 at 09 54 38@2x" src="https://user-images.githubusercontent.com/6104/170713524-d9ba80b0-ec35-4a60-b47e-bb9e23407a50.png">

2022-05-27 14:01 UTC, jvoisin requested changes

2022-05-27 14:01 UTC, jvoisin commented on colors/nord.vim
> +" Gitsigns
Please move this in the `if has('nvim')` block

2022-05-27 15:51 UTC, jvoisin commented on colors/nord.vim
> +" Gitsigns
In the one from line 562, no need to create a new condition :)

2022-05-27 16:50 UTC, jvoisin approved these changes

2022-05-31 16:08 UTC, svengreb approved these changes
Hi @jasonlong :wave:, thanks for your contribution :+1:

Looks good to me and consistent with other plugins/features, even though the support for Neovim specific plugins will be moved to an [upcoming "Nord Neovim" port][1] we can still add it for the time being 👍🏼

[1]: https://github.com/arcticicestudio/nord/issues/157#issuecomment-924312218

2022-05-31 16:09 UTC, arcticicestudio approved these changes

2022-05-31 16:14 UTC, merged

2022-05-31 16:30 UTC, jasonlong commented
Very excited for the Neovim port! 🙌🏼